export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM";
export const UPDATE_TODO_ITEM = "UPDATE_TODO_ITEM";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const COMPLETE_TODO_ITEM = "COMPLETE_TODO_ITEM";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const SET_TODO_LIST = "SET_TODO_LIST";
export const SET_TMP_TODO_LIST = "SET_TMP_TODO_LIST";
